---
image: newcity/builder

before_script:
  - mv ci/Makefile .
  - eval $(ssh-agent -s)
  - ssh-add <(echo "$PIPELINES_PRIVATE_KEY")
  - make init

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - yarn global add patch-package
    - yarn
    - gulp buildAll --min
  artifacts:
    paths:
      - endpoint

deploy:
  stage: deploy
  script:
    - make push_production
  only:
    - master

pages:
  stage: deploy
  script:
    - zip -r dist.zip endpoint
    - mkdir public
    - mv dist.zip public/
    - echo '<a href="dist.zip">dist.zip</a>' > public/index.html
  artifacts:
    paths:
      - public
  only:
    - master

docker:
  stage: deploy
  image: docker:lastest
  variables:
    DOCKER_BUILDKIT: "1"
    DOCKER_DRIVER: overlay2
    IMAGE_NAME: newcity/frontback
    BUILDX_VERSION: "v0.4.1"
  services:
    - docker:dind
  script:
    - apk add curl
    - mkdir -vp ~/.docker/cli-plugins/ ~/dockercache
    - curl --silent -L "https://github.com/docker/buildx/releases/download/${BUILDX_VERSION}/buildx-${BUILDX_VERSION}.linux-amd64" > ~/.docker/cli-plugins/docker-buildx
    - chmod a+x ~/.docker/cli-plugins/docker-buildx
    - docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
    - docker login --username $HUB_USERNAME --password $HUB_PASSWORD

    - docker buildx create --use
    - docker buildx inspect --bootstrap
    - docker buildx build --push --platform linux/amd64,linux/arm64 --no-cache -t $IMAGE_NAME:latest .
  only:
    - master

