---
image: newcity/builder:latest

before_script:
  - eval $(ssh-agent -s)
  - ssh-add <(echo "$PIPELINES_PRIVATE_KEY")
  - make .ci_init
  
cache:
  paths:
    - node_modules/
  
stages:
  - build
  - deploy
  
build:
  stage: build
  script:
    - npm install --silent
    - gulp build-all --min
  artifacts:
    paths:
      - endpoint
  
deploy:
  stage: deploy
  script:
    - make .ci_push_production
  only:
    - master

pages:
  stage: deploy
  script:
    - zip -d endpoint.zip endpoint
    - mkdir public
    - mv endpoint.zip public/
    - echo '<a href="endpoint.zip">artifact</a>' > public/index.html
  artifacts:
    paths:
      - public