---
image: newcity/builder:gulp4

before_script:
  - eval $(ssh-agent -s)
  - ssh-add <(echo "$PIPELINES_PRIVATE_KEY")
  - make .ci_init

stages:
  - build
  - deploy
  
build:
  stage: build
  script:
    - npm install
    - gulp buildAll --min
  artifacts:
    paths:
      - endpoint
  
deploy:
  stage: deploy
  script:
    - make .ci_push_production
  only:
    - master

pages:
  stage: deploy
  script:
    - zip -r dist.zip endpoint
    - mkdir public
    - mv dist.zip public/
    - echo '<a href="dist.zip">dist.zip</a>' > public/index.html
  artifacts:
    paths:
      - public